### ISSUE TITLE
Getting ready for source maps

### ISSUE THREAD

**Issue by avanderhoorn** [sindresorhus/gulp-react#18]
With the next release of `react-tools` support for source maps will be coming to the table - https://github.com/facebook/react/commit/fc5bb9c9b254e3646b90f6b6ce37bfaf64f1129f. 

Normally this would just work as the options are just passed straight through, but its seems like it mightn't be quite that simple. The trouble as I see it, is that to support inline maps, the `transform` function needs to know `options.sourceFilename`. This `sourceFilename` [should](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.lmz475t4mvbx) be the:
 > When the source mapping URL is not absolute, then it is relative to the generated code’s “source origin”.

With my knowledge of Gulp, this is a problem for `gulp-react` is that the user isn't going to be able to set this property, as it needs to change for every file in the stream. Hence, it seems like some minor changes are needed to support this functionality.

Being new to Gulp I'm not 100% sure what the "Gulp" way of doing this would be to derive a relative path from `file` (maybe replace the content of `file.cwd` in `file.path` with *nothing*). But this doesn't seem quite right to me and I'm sure this problem has come up before (deriving relative paths from a `file` stream that would work for a case like this).

I'm happy to help out with the work if you are able to provide some input.

**Comment by sindresorhus** [comment]
@avanderhoorn friendly ping :)
