### ISSUE TITLE
React 13

### ISSUE THREAD

**Issue by Microx** [sindresorhus/gulp-react#31]
Hi,

Why do you add react 13 rc1? 

I use es6 imports and I get error: Illegal import declaration, when I transform jsx files. For gulp-react version 2.0.0 is everything ok.  I used options {harmony: true}, but that doesn't effect for it.

Thanks

**Comment by sindresorhus** [comment]
Ah, yeah. Should probably have been a major release.

**Comment by ssalat** [comment]
@sindresorhus "Ah, yeah. Should probably have been a major release."?

**Comment by sindresorhus** [comment]
React 13 changes a lot of things. Any problems with the output should be posted on the React tracker.

This plugin just passes your options to React and uses the output: https://github.com/sindresorhus/gulp-react/blob/e6e057e8e7ed60cb3282fe758a135b6cf1d76893/index.js#L30
