### ISSUE TITLE
harmony option should be renamed es6module in 3.0.0 doc

### ISSUE THREAD

**Issue by joIivier** [sindresorhus/gulp-react#32]
My build using gulp-react on ES6 classes does not work anymore in version 3.0.0 although it worked correctly on 2.0.0.
The plugin throws an "Illegal import declaration" on valid ES6 code. After some research it seems to be similar to: https://github.com/floatdrop/plugin-jsx/issues/7 . Basically react-tools changed the name of the option they use to switch to harmony parsing.
So I replaced my {harmony:true} by {es6module:true} in the options I pass to gulp-react and it now works; so the doc might need to be updated.

**Comment by sindresorhus** [comment]
It's a separate option though. Not a replacement https://github.com/facebook/react/pull/3143/files

PR welcome for doc changes.

**Comment by sindresorhus** [comment]
Actually, I don't document the options, so should be an issue on React.
