### ISSUE TITLE
How I can use gulp-react with Flow?

### ISSUE THREAD

**Issue by RinatMullayanov** [sindresorhus/gulp-react#35]
I want to use gulp-react with Flow and see error like this:
```
01_HelloWorld/hello.js:7:5,17: string
This type is incompatible with
  01_HelloWorld/hello.js:4:10,13: number
```
for this sample code:
```javascript
/* @flow */

function foo(x) {
  return x * 10;
}

foo('Hello, world!');
```
It is possible?

**Comment by sindresorhus** [comment]
I have no idea what you're asking, but compiling react and using flow are completely different and done in different steps. Try asking on StackOverflow.

**Comment by RinatMullayanov** [comment]
I just thought that the gulp-react same as [jstransform]( https://www.npmjs.com/package/jstransform ) only gulp, and jstransform is able to transform flow + jsx.
