### ISSUE TITLE
Deprecate gulp-react in favor of gulp-babel

### ISSUE THREAD

**Issue by jfache** [sindresorhus/gulp-react#37]
As per this post (https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html), the React dev team is deprecating react-tools and invite developers to migrate to Babel.

The migration is trivial. Since this plugin comes first when you look for a gulp plugin for React, and since we should promote recommended implementation (Babel as of now), it would be nice if the README of this project could mention the deprecation and link to gulp-babel.

What do you think?

**Comment by arthurvr** [comment]
Let's hear what Sindre thinks, but that sounds like the right thing to do, yeah :+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by kevva** [comment]
Let's do it.
