### ISSUE TITLE
Task ignores case in file names

### ISSUE THREAD

**Issue by abhinavsingi** [sindresorhus/gulp-react#38]
Ex. I have a 'tableList.jsx' and hence I want 'tableList.js' - It will be generated
But if I rename it to 'TableList.jsx' then I would want 'TableList.js' - but it isn't generated as 'tableList.js' already exists.

**Comment by sindresorhus** [comment]
This task only changes the file extension. Your problem is elsewhere. Try asking on StackOverflow.
